export type Vehicle = {
  id: string;
  category: "MPV" | "Sedan" | "Motorcycle";
  name: string;
  type: string;
  year: string;
  fuel: string;
  transmission: string;
  seats: string;
  doors: string;
  price1Label: string;
  price1: string;
  price2Label: string;
  price2: string;
  image: string;
  isAvailable: boolean;
  description: string;
  features: string[];
};

const defaultCarFeatures = [
  "Air Conditioning",
  "Bluetooth Connectivity",
  "USB Ports",
  "Power Steering",
  "ABS Brakes",
  "Airbags",
];

const defaultMotoFeatures = [
  "Electric Starter",
  "Spacious Trunk",
  "Digital Panel Meter",
  "Keyless Ignition",
];

export const vehicleData: Vehicle[] = [
  // --- 6 MPV & VAN ---
  {
    id: "mpv-1",
    category: "MPV",
    name: "Toyota Innova",
    type: "Type G",
    year: "2022",
    fuel: "Diesel",
    transmission: "Automatic",
    seats: "7 Seaters",
    doors: "4 Doors",
    price1Label: "Self-Drive 24h",
    price1: "Rp. 450.000",
    price2Label: "With Driver 24h",
    price2: "Rp. 550.000",
    image: "/cars/mpv/car-1.avif",
    isAvailable: true,
    description:
      "Toyota Innova adalah pilihan sempurna untuk perjalanan keluarga atau grup bisnis. Menawarkan kabin yang luas, suspensi nyaman, dan mesin diesel yang tangguh serta irit bahan bakar.",
    features: [...defaultCarFeatures, "Rear Camera", "Spacious Cabin"],
  },
  {
    id: "mpv-2",
    category: "MPV",
    name: "Toyota Avanza",
    type: "Type G",
    year: "2024",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: "7 Seaters",
    doors: "4 Doors",
    price1Label: "Self-Drive 24h",
    price1: "Rp. 250.000",
    price2Label: "With Driver 24h",
    price2: "Rp. 350.000",
    image: "/cars/mpv/car-2.avif",
    isAvailable: true,
    description:
      "Mobil MPV sejuta umat yang sangat cocok untuk perjalanan dalam dan luar kota. Desain baru yang lebih modern dengan efisiensi bahan bakar maksimal.",
    features: [...defaultCarFeatures, "Touchscreen Audio"],
  },
  {
    id: "mpv-3",
    category: "MPV",
    name: "Toyota Alphard",
    type: "Hybrid",
    year: "2025",
    fuel: "Hybrid",
    transmission: "Automatic",
    seats: "7 Seaters",
    doors: "4 Doors",
    price1Label: "Self-Drive 24h",
    price1: "Rp. 1.500.000",
    price2Label: "With Driver 24h",
    price2: "Rp. 1.700.000",
    image: "/cars/mpv/car-3.avif",
    isAvailable: true,
    description:
      "Nikmati kemewahan kelas atas dengan Toyota Alphard. Dilengkapi dengan kursi captain seat, sunroof, dan peredaman kabin yang luar biasa hening.",
    features: [
      ...defaultCarFeatures,
      "Captain Seats",
      "Sunroof",
      "Premium Audio",
    ],
  },
  {
    id: "mpv-4",
    category: "MPV",
    name: "Toyota Hiace Premio",
    type: "Commuter",
    year: "2022",
    fuel: "Diesel",
    transmission: "Manual",
    seats: "12 Seaters",
    doors: "4 Doors",
    price1Label: "With Driver 12h",
    price1: "Rp. 800.000",
    price2Label: "With Driver 24h",
    price2: "Rp. 1.500.000",
    image: "/cars/mpv/car-4.avif",
    isAvailable: false,
    description:
      "Van premium dengan kapasitas besar. Sangat ideal untuk rombongan wisata atau perjalanan korporat dengan tingkat kenyamanan tinggi di setiap baris kursinya.",
    features: [
      "Dual Zone AC",
      "Reclining Seats",
      "Reading Lights",
      "Large Luggage Space",
    ],
  },
  {
    id: "mpv-5",
    category: "MPV",
    name: "Mitsubishi Xpander",
    type: "Ultimate",
    year: "2023",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: "7 Seaters",
    doors: "4 Doors",
    price1Label: "Self-Drive 24h",
    price1: "Rp. 300.000",
    price2Label: "With Driver 24h",
    price2: "Rp. 400.000",
    image: "/cars/mpv/car-5.avif",
    isAvailable: true,
    description:
      "MPV bergaya SUV dengan ground clearance tinggi. Cocok untuk berbagai medan jalan di Indonesia tanpa mengorbankan kenyamanan penumpang.",
    features: [...defaultCarFeatures, "Cruise Control", "Keyless Entry"],
  },
  {
    id: "mpv-6",
    category: "MPV",
    name: "Suzuki Ertiga",
    type: "Hybrid",
    year: "2023",
    fuel: "Hybrid",
    transmission: "Automatic",
    seats: "7 Seaters",
    doors: "4 Doors",
    price1Label: "Self-Drive 24h",
    price1: "Rp. 250.000",
    price2Label: "With Driver 24h",
    price2: "Rp. 350.000",
    image: "/cars/mpv/car-6.avif",
    isAvailable: true,
    description:
      "Kendaraan keluarga yang ramah lingkungan dengan teknologi Smart Hybrid. Menawarkan efisiensi tinggi dengan kabin interior yang mewah.",
    features: [
      ...defaultCarFeatures,
      "Smart Hybrid Tech",
      "Ventilated Cup Holders",
    ],
  },

  // --- 5 SEDAN ---
  {
    id: "sedan-1",
    category: "Sedan",
    name: "Honda Civic",
    type: "RS",
    year: "2023",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: "5 Seaters",
    doors: "4 Doors",
    price1Label: "Self-Drive 24h",
    price1: "Rp. 600.000",
    price2Label: "With Driver 24h",
    price2: "Rp. 750.000",
    image: "/cars/small-car/car-1.avif",
    isAvailable: true,
    description:
      "Sedan sporty dengan handling tajam dan mesin turbo yang responsif. Menawarkan pengalaman berkendara yang menyenangkan dan dinamis.",
    features: [
      ...defaultCarFeatures,
      "Turbocharged Engine",
      "Honda Sensing",
      "Sport Seats",
    ],
  },
  {
    id: "sedan-2",
    category: "Sedan",
    name: "Toyota Camry",
    type: "V",
    year: "2022",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: "5 Seaters",
    doors: "4 Doors",
    price1Label: "Self-Drive 24h",
    price1: "Rp. 800.000",
    price2Label: "With Driver 24h",
    price2: "Rp. 1.000.000",
    image: "/cars/small-car/car-2.avif",
    isAvailable: false,
    description:
      "Simbol eksekutif mapan. Toyota Camry menghadirkan kursi berlapis kulit premium, suspensi yang sangat empuk, dan prestise tingkat tinggi.",
    features: [
      ...defaultCarFeatures,
      "Leather Seats",
      "Power Rear Sunshade",
      "Wireless Charger",
    ],
  },
  {
    id: "sedan-3",
    category: "Sedan",
    name: "Honda Accord",
    type: "Turbo",
    year: "2024",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: "5 Seaters",
    doors: "4 Doors",
    price1Label: "Self-Drive 24h",
    price1: "Rp. 850.000",
    price2Label: "With Driver 24h",
    price2: "Rp. 1.050.000",
    image: "/cars/small-car/car-3.avif",
    isAvailable: true,
    description:
      "Sedan premium Honda dengan teknologi keselamatan terdepan dan kabin yang sangat luas, ideal untuk perjalanan bisnis Anda.",
    features: [
      ...defaultCarFeatures,
      "Honda Sensing",
      "Memory Seats",
      "Active Noise Cancellation",
    ],
  },
  {
    id: "sedan-4",
    category: "Sedan",
    name: "Honda City",
    type: "V",
    year: "2022",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: "5 Seaters",
    doors: "4 Doors",
    price1Label: "Self-Drive 24h",
    price1: "Rp. 400.000",
    price2Label: "With Driver 24h",
    price2: "Rp. 550.000",
    image: "/cars/small-car/car-4.avif",
    isAvailable: true,
    description:
      "Compact sedan yang tangkas untuk rute perkotaan. Sangat mudah diparkir dan irit bahan bakar.",
    features: [
      ...defaultCarFeatures,
      "Remote Engine Start",
      "Multi-Angle Rear Camera",
    ],
  },
  {
    id: "sedan-5",
    category: "Sedan",
    name: "Mazda 3",
    type: "Sedan",
    year: "2023",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: "5 Seaters",
    doors: "4 Doors",
    price1Label: "Self-Drive 24h",
    price1: "Rp. 550.000",
    price2Label: "With Driver 24h",
    price2: "Rp. 700.000",
    image: "/cars/small-car/car-5.avif",
    isAvailable: true,
    description:
      "Desain KODO khas Mazda yang indah dipandang dengan interior premium driver-centric yang memberikan kenyamanan ekstra bagi pengemudi.",
    features: [
      ...defaultCarFeatures,
      "Bose Audio System",
      "Heads-up Display",
      "Premium Leather",
    ],
  },

  // --- 3 MOTORCYCLE ---
  {
    id: "moto-1",
    category: "Motorcycle",
    name: "Vespa Sprint",
    type: "150 i-get",
    year: "2023",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: "2 Seaters",
    doors: "0 Doors",
    price1Label: "Self-Drive 12h",
    price1: "Rp. 100.000",
    price2Label: "Self-Drive 24h",
    price2: "Rp. 150.000",
    image: "/motorcycle/moto-1.avif",
    isAvailable: true,
    description:
      "Skuter klasik ikonik dari Italia. Sangat stylish untuk berkeliling kota dengan gaya yang timeless dan mesin i-get yang halus.",
    features: [...defaultMotoFeatures, "ABS Brakes", "LED Headlights"],
  },
  {
    id: "moto-2",
    category: "Motorcycle",
    name: "Yamaha NMAX",
    type: "155 Connected",
    year: "2024",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: "2 Seaters",
    doors: "0 Doors",
    price1Label: "Self-Drive 12h",
    price1: "Rp. 80.000",
    price2Label: "Self-Drive 24h",
    price2: "Rp. 120.000",
    image: "/motorcycle/moto-2.avif",
    isAvailable: true,
    description:
      "Skuter Maxi paling populer di Indonesia. Posisi berkendara santai dengan pijakan kaki luas, nyaman untuk riding jarak jauh.",
    features: [
      ...defaultMotoFeatures,
      "Y-Connect",
      "Traction Control",
      "Dual Channel ABS",
    ],
  },
  {
    id: "moto-3",
    category: "Motorcycle",
    name: "Honda PCX",
    type: "160 CBS",
    year: "2023",
    fuel: "Petrol",
    transmission: "Automatic",
    seats: "2 Seaters",
    doors: "0 Doors",
    price1Label: "Self-Drive 12h",
    price1: "Rp. 85.000",
    price2Label: "Self-Drive 24h",
    price2: "Rp. 130.000",
    image: "/motorcycle/moto-3.avif",
    isAvailable: false,
    description:
      "Skuter premium elegan dari Honda. Mesin 160cc 4-katup eSP+ menjamin akselerasi mulus dengan bagasi penyimpanan raksasa.",
    features: [
      ...defaultMotoFeatures,
      "USB Power Charger",
      "Hazard Lamp",
      "Idling Stop System",
    ],
  },
];
